fr3d_ldap:
    service:
        user_hydrator: ldap_user_hydrator
    driver:
        host: "%ldap_host%"
        port: "%ldap_port%"
        useSsl: "%ldap_ssl%"
        useStartTls: "%ldap_tls%"
        bindRequiresDn: "%ldap_bind_requires_dn%"
        username: "%ldap_manager_dn%"
        password: "%ldap_manager_pw%"
    user:
        baseDn: "%ldap_base%"
        filter: "%ldap_filter%"
        usernameAttribute: "%ldap_username_attribute%"
security:
    providers:
        chain_provider:
            chain:
                providers: [ fr3d_ldapbundle, fos_userbundle ]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
    firewalls:
        secured_area:
            fr3d_ldap: ~
            form_login:
                provider: chain_provider

fos_oauth_server:
    db_driver:           orm
    client_class:        Wallabag\ApiBundle\Entity\Client
    access_token_class:  Wallabag\ApiBundle\Entity\AccessToken
    refresh_token_class: Wallabag\ApiBundle\Entity\RefreshToken
    auth_code_class:     Wallabag\ApiBundle\Entity\AuthCode
    service:
        user_provider: fr3d_ldap.security.user.provider
        options:
            refresh_token_lifetime: 1209600

